max_width = 120
fn_call_width = 120
comment_width = 120

wrap_comments = true
reorder_imports = true
reorder_modules = true
match_block_trailing_comma = true
condense_wildcard_suffixes = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
normalize_comments = true
reorder_impl_items = true
use_try_shorthand = true
format_strings = true

newline_style = "Unix"
imports_granularity = "Module"

edition = "2021"
