[toolchain]
channel = "nightly-2021-11-11"
components = ["rls", "cargo", "rustfmt", "clippy", "rust-src"]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
profile = "default"