[package]
name = "nolb-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1.0.32"

[dependencies.quote]
version = "1.0.10"

[dependencies.syn]
version = "1.0.81"