[[agents]]
name = "host1"
provider = "hetzner"
applications = ["example_app_docker", "example_app_host"]

    [agents.provider_properties]
    some_prop1 = [1, 3, 4]

    [agents.server_auth]
    ssh_port = 22
    user = "username"
    password = "password"

    [agents.hardware_requirements]
    cpu = 4
    memory = 2_000
    swap_size = 2
    disk_volume = 20
    disk_volume_spread_over = 20
    disk_volume_spread_above = 5
    disk_type = "hdd"
    dist_type_hard_requirement = true

    [agents.autoscaling_policy]
    cpu_load = 90
    memory_load = 95
    swap_load = 80
    factors = 1
    max_instances = 12
    min_instances = 3

[[applications]]
name = "example_app_docker"

    [applications.docker]
    image = "hello-world:latest"
    image_pull_timeout = 30
    timeout = 30
    run_cmd = "docker run --rm %image%"

[[applications]]
name = "example_app_host"

    [applications.host.distribution]
    distributor_id = "Ubuntu"
    release = "20.04"

    [applications.host.packages]
    update = true
    upgrade = true
    install = ["git", "gcc"]
    post_install_commands = ["echo \"hello world!\""]
